server:
  port: 19098

spring:
  application:
    name: promotion-service
  datasource:
    url: jdbc:postgresql://localhost:5432/chat
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_batch_fetch_size: 1000

  # 카프카 설정
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/


# springdoc-openapi-ui
gateway:
  url: http://localhost:19091
springdoc:
  api-docs:
    version: openapi_3_1
    enabled: true
    path: /v3/api-docs
    # 게이트웨이 라우팅에서 prefix를 제거하지 않았다면 해당 설정을 추가
  enable-spring-security: true
  default-consumes-media-type: application/json;charset=UTF-8 # 요청 객체 Data Type
  default-produces-media-type: application/json;charset=UTF-8 # 응답 객체 Data Type