server:
  port: 19093

spring:
  application:
    name: user-service
#  datasource:
#    url: ${DATASOURCE_URL}
#    username: ${DATASOURCE_USERNAME}
#    password: ${DATASOURCE_PASSWORD}
#    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_batch_fetch_size: 1000
  h2:
    console:
      enabled: true  # H2 Console을 사용할지 여부 (H2 Console은 H2 Database를 UI로 제공해주는 기능)
      path: /h2-console  # H2 Console의 Path
    # Database Setting Info (Database를 H2로 사용하기 위해 H2연결 정보 입력)
    datasource:
      driver-class-name: org.h2.Driver  # Database를 H2로 사용하겠다.
      url: jdbc:h2:~/test  # H2 접속 정보
      username: sa  # H2 접속 시 입력할 username 정보 (원하는 것으로 입력)
      password:

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

# springdoc-openapi-ui# springdoc-openapi-ui
gateway:
  url: http://localhost:19091
springdoc:
  api-docs:
    version: openapi_3_1
    enabled: true
    path: /v3/api-docs
    # 게이트웨이 라우팅에서 prefix를 제거하지 않았다면 해당 설정을 추가
  enable-spring-security: true
  default-consumes-media-type: application/json;charset=UTF-8 # 요청 객체 Data Type
  default-produces-media-type: application/json;charset=UTF-8 # 응답 객체 Data Type