server:
  port: 19091

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  cloud:
    gateway:
      routes: # Spring Cloud Gateway의 라우팅 설정
        - id: reservation-service # 예약 서비스
          uri: lb://reservation-service
          predicates:
            - Path=/api/reservations/**, /api/time-slots/**, /api/reviews/**, /api/reports/**, /api/grades/**
        - id: user-service # 사용자 서비스
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**, /api/users/**, /api/profile/**
        - id: post-service # 게시판 서비스
          uri: lb://post-service
          predicates:
            - Path=/api/posts/**, /api/comments/**, /api/multimedia/**
        - id: promotion-service # 프로모션 서비스
          uri: lb://promotion-service
          predicates:
            - Path=/api/promotions/**, /api/coupons/**, /api/my-coupons/**
        - id: chat-service # 채팅 서비스
          uri: lb://chat-service
          predicates:
            - Path=/api/chat/**
        - id: payment-service # 결제 서비스
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**
        - id: notification-service # 알림 서비스
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
        - id: auth-service # 알림 서비스
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**

      discovery:
        locator:
          enabled: true # 서비스 디스커버리를 통해 동적으로 라우트를 생성하도록 설정

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/ # Eureka 서버의 URL을 지정


springdoc:
  swagger-ui:
    path: /swagger
    urls[0]:
      name: reservation service
      url: http://localhost:19092/v3/api-docs
    urls[1]:
      name: user service
      url: http://localhost:19093/v3/api-docs
    urls[2]:
      name: notification service
      url: http://localhost:19094/v3/api-docs
    urls[3]:
      name: post service
      url: http://localhost:19095/v3/api-docs
    urls[4]:
      name: payment service
      url: http://localhost:19096/v3/api-docs
    urls[5]:
      name: chat service
      url: http://localhost:19097/v3/api-docs
    urls[6]:
      name: promotion service
      url: http://localhost:19098/v3/api-docs
    urls[7]:
      name: auth service
      url: http://localhost:19099/v3/api-docs

