server:
  port: 19091

spring:
  config:
    activate:
      on-profile: local

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/ # Eureka 서버의 URL을 지정

springdoc:
  swagger-ui:
    path: /swagger
    urls[0]:
      name: reservation service
      url: http://localhost:19092/v3/api-docs
    urls[1]:
      name: user service
      url: http://localhost:19093/v3/api-docs
    urls[2]:
      name: notification service
      url: http://localhost:19094/v3/api-docs
    urls[3]:
      name: post service
      url: http://localhost:19095/v3/api-docs
    urls[4]:
      name: payment service
      url: http://localhost:19096/v3/api-docs
    urls[5]:
      name: chat service
      url: http://localhost:19097/v3/api-docs
    urls[6]:
      name: promotion service
      url: http://localhost:19098/v3/api-docs
    urls[7]:
      name: auth service
      url: http://localhost:19099/v3/api-docs

