server:
  port: 19091

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  cloud:
    gateway:
      routes: # Spring Cloud Gateway의 라우팅 설정
        - id: reservation-service
          uri: lb://reservation-service
          predicates:
            - Path=/api/reservations/**
      discovery:
        locator:
          enabled: true # 서비스 디스커버리를 통해 동적으로 라우트를 생성하도록 설정

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/ # Eureka 서버의 URL을 지정
