server:
  port: 19090

spring:
  config:
    activate:
      on-profile: local

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:19090/eureka/
  instance:
    hostname: localhost